# Site settings
title: Epilepsy Drug Database 
email: sruggless@flexion.us
description: > # this means to ignore newlines until "baseurl:"
  Prototype search application for 18F 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
